### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by krvikas1011** [krvikas1011/method-parser#4]
**Requirements**:
- [x] Create a phase-wise project plan along with timelines. 
- [ ] Approval and agreement to plan by all collaborators.

**Definition of done**:
- [ ] The Project plan is finalized and added as a plan document in the repo.
